name: Publish Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Build
        run: |
          go mod download
          go build ./...

      - name: Run tests
        run: go test -v ./...

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            releases/featherjet-linux-amd64
            releases/featherjet-windows-amd64.exe
            releases/featherjet-darwin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}